openapi: 3.0.1
info:
  title: Bybit Spot Price API
  version: '1.0'
paths:
  /price/{symbol}:
    get:
      summary: Get full spot trading data for a crypto symbol
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol:
                    type: string
                  lastPrice:
                    type: string
                  highPrice24h:
                    type: string
                  lowPrice24h:
                    type: string
                  turnover24h:
                    type: string
                  price24hPcnt:
                    type: string
                  bid1Price:
                    type: string
                  ask1Price:
                    type: string
                  bid1Qty:
                    type: string
                  ask1Qty:
                    type: string
  /market-scan:
    get:
      summary: Get a list of symbols with 24h trading volume over $10 million
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    symbol:
                      type: string
                    lastPrice:
                      type: string
                    turnover24h:
                      type: string
                    price24hPcnt:
                      type: string
